/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accenture.view;

import com.accenture.control.ManipulaDadosSQLite;
import com.accenture.bean.Step;
import com.accenture.bean.StepPadrao;

import com.accenture.util.TextAreaCellEditor;
import com.accenture.util.TextAreaCellRenderer;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author raphael.da.silva
 */
public class EditStepDefaultScreenView extends javax.swing.JInternalFrame {
private ManipulaDadosSQLite banco = new ManipulaDadosSQLite();
    /**
     * Creates new form GUISelecionaStepPadrao
     */
    public EditStepDefaultScreenView() throws IOException, ClassNotFoundException, SQLException{
        initComponents();
        pack();
        new SwingWorker() {
            JDialog aguarde;
            final Frame GUIPrincipal = new MainScreenView();
            {
                this.aguarde = new WaitScreenView((JFrame) GUIPrincipal, true);
            }
            @Override
            protected Object doInBackground() throws Exception {
                aguarde.setLocationRelativeTo(GUIPrincipal);
                aguarde.setVisible(true);
                atualizaTabelaStepPadrao();
                return null;
            }

            @Override
            protected void done() {
                aguarde.dispose();
            }

        }.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPesquisaCT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMatemStepPadrao = new javax.swing.JTable();
        bntNovoStep = new javax.swing.JButton();
        bntCopiar1 = new javax.swing.JButton();
        bntCopiar2 = new javax.swing.JButton();
        bntCopiar3 = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciar Steps Padrão");
        setName("teste"); // NOI18N

        textPesquisaCT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPesquisaCTKeyPressed(evt);
            }
        });

        tabelaMatemStepPadrao.addMouseMotionListener(new MouseMotionAdapter(){
            public void mouseMoved(MouseEvent e){
                Point p = e.getPoint();
                int row = tabelaMatemStepPadrao.rowAtPoint(p);
                int column = tabelaMatemStepPadrao.columnAtPoint(p);
                tabelaMatemStepPadrao.setToolTipText(String.valueOf(tabelaMatemStepPadrao.getValueAt(row,column)));
            }//end MouseMoved
        });
        tabelaMatemStepPadrao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DESCRIÇÃO", "RESULTADO ESPERADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaMatemStepPadrao.setColumnSelectionAllowed(true);
        tabelaMatemStepPadrao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaMatemStepPadrao);
        tabelaMatemStepPadrao.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tabelaMatemStepPadrao.getColumnModel().getColumnCount() > 0) {
            tabelaMatemStepPadrao.getColumnModel().getColumn(0).setResizable(false);
            tabelaMatemStepPadrao.getColumnModel().getColumn(0).setCellEditor(new TextAreaCellEditor());
            tabelaMatemStepPadrao.getColumnModel().getColumn(1).setResizable(false);
            tabelaMatemStepPadrao.getColumnModel().getColumn(1).setCellEditor(new TextAreaCellEditor());
        }
        TableColumn col;
        for (int i = 0; i < tabelaMatemStepPadrao.getColumnCount(); i++) {
            col = tabelaMatemStepPadrao.getColumnModel().getColumn(i);
            col.setCellRenderer(new TextAreaCellRenderer());
        }

        bntNovoStep.setText("Novo");
        bntNovoStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntNovoStepMouseClicked(evt);
            }
        });

        bntCopiar1.setText("Salvar");
        bntCopiar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntCopiar1MouseClicked(evt);
            }
        });

        bntCopiar2.setText("Excluir");
        bntCopiar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntCopiar2MouseClicked(evt);
            }
        });

        bntCopiar3.setText("Cancelar");
        bntCopiar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntCopiar3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPesquisaCT)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(bntNovoStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntCopiar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntCopiar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntCopiar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPesquisaCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntNovoStep)
                    .addComponent(bntCopiar1)
                    .addComponent(bntCopiar2)
                    .addComponent(bntCopiar3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPesquisaCTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPesquisaCTKeyPressed
        //Realiza pesquisa na tabela
        DefaultTableModel tabelaCT = (DefaultTableModel) tabelaMatemStepPadrao.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabelaCT);
        tabelaMatemStepPadrao.setRowSorter(sorter);
        String busca = textPesquisaCT.getText();
        if (busca.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(RowFilter.regexFilter(busca, 0));
            } catch (PatternSyntaxException pse) {
                System.err.println("Erro");
            }
        }
    }//GEN-LAST:event_textPesquisaCTKeyPressed

    private void bntNovoStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntNovoStepMouseClicked
        
    }//GEN-LAST:event_bntNovoStepMouseClicked

    private void bntCopiar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCopiar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bntCopiar1MouseClicked

    private void bntCopiar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCopiar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bntCopiar2MouseClicked

    private void bntCopiar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCopiar3MouseClicked
        this.dispose();
    }//GEN-LAST:event_bntCopiar3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCopiar1;
    private javax.swing.JButton bntCopiar2;
    private javax.swing.JButton bntCopiar3;
    private javax.swing.JButton bntNovoStep;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaMatemStepPadrao;
    private javax.swing.JTextField textPesquisaCT;
    // End of variables declaration//GEN-END:variables

    public void centralizaJanela() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
       
    }
    
    public void atualizaTabelaStepPadrao() {
        DefaultTableModel model = (DefaultTableModel) tabelaMatemStepPadrao.getModel();
        if (model.getRowCount() != 0) {
            int numLinhas = model.getRowCount();
            for (int i = 0; i <= model.getRowCount(); i++) {
                //                model.removeRow(0);
                model.setRowCount(0);
            }
        }
        
        try {

            //Adiciona os casos de teste na tabela caso de teste
            List<StepPadrao> listStep = banco.getAllStepPadrao();

            int tamanho = listStep.size();
            int idTemp = 0;
            for (int cont = 0; cont < tamanho; cont++) {

                if (idTemp != listStep.get(cont).getId()) {
                    model.addRow(new String[]{listStep.get(cont).getDescStep(), listStep.get(cont).getResultadoStep()});
                    
                }
                idTemp = listStep.get(cont).getId();

            }

        } catch (SQLException ex) {
           
        } catch (ClassNotFoundException ex) {
            
        }

        }

}

