/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accenture.view;

import com.accenture.bean.ButtonIconBean;
import com.accenture.control.ManipulaDadosSQLite;
import com.accenture.bean.Plano;
import com.inet.jortho.FileUserDictionary;
import com.inet.jortho.SpellChecker;
import java.awt.Dimension;
import java.awt.Frame;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingWorker;

/**
 *
 * @author raphael.da.silva
 */
public class FilterTestCaseScreen1View extends java.awt.Dialog {

    private ManipulaDadosSQLite banco = new ManipulaDadosSQLite();
    private EditTestCaseScreenTIView guiMatemCt;
    private ButtonIconBean icon;

    /**
     * Creates new form GUIFiltroCT
     */
    public FilterTestCaseScreen1View(java.awt.Frame parent, boolean modal) throws SQLException, ClassNotFoundException {
        super(parent, modal);

        initComponents();
    }

    public FilterTestCaseScreen1View(final EditTestCaseScreenTIView guiMantemCT, java.awt.Frame parent, boolean modal) throws IOException, ClassNotFoundException, SQLException {
        super(parent, modal);

        this.setResizable(false);
        initComponents();
        this.guiMatemCt = guiMantemCT;
        new SwingWorker() {
            JDialog aguarde;
            final Frame GUIPrincipal = new MainScreenView();

            {
                this.aguarde = new WaitScreenView((JFrame) GUIPrincipal, true);
            }

            @Override
            protected Object doInBackground() throws Exception {
                aguarde.setLocationRelativeTo(GUIPrincipal);
                aguarde.setVisible(true);
                // carregando os combobox
                List<String> criacao = banco.selectConfALL("TB_CRIACAO");
                List<String> sistemaMaster = banco.selectConfALL("TB_SISTEMA_MASTER");
                List<String> type = banco.selectConfALL("TB_TYPE");
                List<String> trg = banco.selectConfALL("TB_TRG");

                //Carrega comboBox criação com os dados da tabela
                int tamanhoCriacao = criacao.size();
                for (int cont = 0; cont < tamanhoCriacao; cont++) {
                    comboCriacao.addItem(criacao.get(cont));
                }

                //Carrega comboBox sistema master com os dados da tabela
                int tamanhoSistemaMaster = sistemaMaster.size();
                for (int cont = 0; cont < tamanhoSistemaMaster; cont++) {
                    comboSistemaMaster.addItem(sistemaMaster.get(cont));
                }
                //Carrega comboBox trg com os dados da tabela
                int tamanhoTrg = trg.size();
                for (int cont = 0; cont < tamanhoTrg; cont++) {

                    comboTrg.addItem(trg.get(cont));
                }
                
                

                return null;
            }

            @Override
            protected void done() {
                aguarde.dispose();
            }

        }.execute();

        /*
        **Carregando os ícones dos botões:
        */
        
        icon = new ButtonIconBean();
        this.addIconInButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        textNomeCT = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        comboSistemaMaster = new javax.swing.JComboBox();
        jLabel51 = new javax.swing.JLabel();
        comboCriacao = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        textSistemaEnvolvidos = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        comboTrg = new javax.swing.JComboBox();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TextAreaDescricao = new javax.swing.JTextArea();
        bntCancelar = new javax.swing.JButton();
        bntPesquisar = new javax.swing.JButton();

        setTitle("Filtro - Caso de Teste");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(380, 455));

        jLabel50.setForeground(new java.awt.Color(51, 51, 51));
        jLabel50.setText("NOME CT:");

        textNomeCT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textNomeCT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNomeCTFocusLost(evt);
            }
        });

        jLabel33.setText("SISTEMA MASTER:");

        jLabel51.setText("CRIAÇÃO/ALTERAÇÃO");

        jLabel34.setText("SISTEMAS ENVOLVIDOS:");

        textSistemaEnvolvidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSistemaEnvolvidosFocusLost(evt);
            }
        });

        jLabel46.setText("TRG:");
        jLabel46.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel46AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel52.setText("DESCRIÇÃO:");

        TextAreaDescricao.setColumns(20);
        TextAreaDescricao.setRows(5);
        TextAreaDescricao.setWrapStyleWord(true);
        TextAreaDescricao.setDragEnabled(true);
        TextAreaDescricao.setPreferredSize(new java.awt.Dimension(90, 94));
        SpellChecker.setUserDictionaryProvider(new FileUserDictionary());
        SpellChecker.registerDictionaries(null, null);
        SpellChecker.register(TextAreaDescricao);
        jScrollPane8.setViewportView(TextAreaDescricao);
        //JScrollPane scrollPane;
        //scrollPane = new JScrollPane(TextAreaDescricao);
        TextAreaDescricao.setLineWrap(true);
        TextAreaDescricao.setDragEnabled(true);

        bntCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bntCancelar.setText("Cancelar");
        bntCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntCancelarMouseClicked(evt);
            }
        });

        bntPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bntPesquisar.setText("Pesquisar");
        bntPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntPesquisarMouseClicked(evt);
            }
        });
        bntPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(bntPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntCancelar)
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50)
                            .addComponent(jLabel1)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNomeCT)
                            .addComponent(comboSistemaMaster, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textSistemaEnvolvidos)
                            .addComponent(comboTrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboCriacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane8))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(textNomeCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33))
                    .addComponent(comboSistemaMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(textSistemaEnvolvidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(comboTrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCancelar)
                    .addComponent(bntPesquisar))
                .addContainerGap())
        );

        comboSistemaMaster.addItem("");
        comboCriacao.addItem("");
        comboTrg.addItem("");

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void textNomeCTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNomeCTFocusLost

    }//GEN-LAST:event_textNomeCTFocusLost

    private void textSistemaEnvolvidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSistemaEnvolvidosFocusLost


    }//GEN-LAST:event_textSistemaEnvolvidosFocusLost

    private void jLabel46AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel46AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel46AncestorAdded

    private void bntCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_bntCancelarMouseClicked

    private void bntPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntPesquisarMouseClicked
        
        SwingWorker sw = new SwingWorker() {
            JDialog aguarde;
            final Frame GUIPrincipal = new MainScreenView();
            {
                this.aguarde = new WaitScreenView((JFrame) GUIPrincipal, true);
            }
            
            boolean filtro = false;
            
            List<Plano> listPlano = new ArrayList<Plano>();
            String and = " and ";
            String sql = "SELECT * FROM TB_PLANOS P, TB_STEPS S WHERE P.ID = S.ID_PLANO ";
            String query = "";
            String sqlNomeCT = " AND CASO_TESTE LIKE" + " '%" + textNomeCT.getText() + "%' ";
            String sqlSistemaMaster = " AND SISTEMA_MASTER LIKE" + " '%" + comboSistemaMaster.getSelectedItem().toString() + "%'";
            String sqlSistemaEnvolvidos = " AND SISTEMAS_ENVOLVIDOS LIKE" + " '%" + textSistemaEnvolvidos.getText() + "%' ";
            String sqlTrg = " AND TRG LIKE" + " '%" + comboTrg.getSelectedItem().toString() + "%' ";
            String sqlCriacao = " AND CRIACAO_ALTERACAO LIKE" + " '%" + comboCriacao.getSelectedItem().toString() + "%' ";
            String sqlDescricao = " AND DESCRICAO_CASO_TESTE LIKE" + " '%" + TextAreaDescricao.getText() + "%' ";

            @Override
            protected Object doInBackground() throws Exception {
                aguarde.setLocationRelativeTo(GUIPrincipal);
                aguarde.setVisible(true);
                if (!textNomeCT.getText().equals("")) {
                    sql = sql + sqlNomeCT;
                    filtro = true;
                }

                if (!comboSistemaMaster.getSelectedItem().toString().equals("")) {
                    sql = sql + sqlSistemaMaster;
                    filtro = true;
                }

                if (!textSistemaEnvolvidos.getText().equals("")) {
                    sql = sql + sqlSistemaEnvolvidos;
                    filtro = true;
                }

                if (!comboTrg.getSelectedItem().toString().equals("")) {
                    sql = sql + sqlTrg;
                    filtro = true;
                }

                if (!TextAreaDescricao.getText().equals("")) {
                    sql = sql + sqlDescricao;
                    filtro = true;
                }
                
                if (!comboCriacao.getSelectedItem().toString().equals("")) {
                    sql = sql + sqlCriacao;
                    filtro = true;
                }

                System.out.println(sql);
                listPlano = banco.getCTsPorQuery(sql);
                
                atualizaTabelaPlanosGUIMatem(listPlano);
                return null;

            }

            @Override
            protected void done() {
                aguarde.dispose();
            }
        };
        sw.execute();
        this.dispose();


    }//GEN-LAST:event_bntPesquisarMouseClicked

    private void bntPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FilterTestCaseScreen1View dialog = null;
                try {
                    dialog = new FilterTestCaseScreen1View(new java.awt.Frame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(FilterTestCaseScreen1View.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FilterTestCaseScreen1View.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaDescricao;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JComboBox comboCriacao;
    private javax.swing.JComboBox comboSistemaMaster;
    private javax.swing.JComboBox comboTrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField textNomeCT;
    private javax.swing.JTextField textSistemaEnvolvidos;
    // End of variables declaration//GEN-END:variables

    public void centralizaJanelaDialogo(EditTestCaseScreenTIView tela) {
        Dimension d = tela.getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    public void atualizaTabelaPlanosGUIMatem(List<Plano> listPlano) throws SQLException, ClassNotFoundException{
        
        guiMatemCt.atualizaTabelaPlano(listPlano);
    }
    
     public void addIconInButton(){
        
        bntCancelar.setIcon(icon.getIconBntCacelAction());
        bntPesquisar.setIcon(icon.getIconBntSearchCt());
    }
}
