/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accenture.view;

import com.accenture.control.ImportaStepPadrao;
import com.accenture.control.ManipulaDadosSQLite;
import com.accenture.bean.StepPadrao;
import java.awt.Dimension;
import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author raphael.da.silva
 */
public class ImportStepDefaultScreenView extends javax.swing.JInternalFrame {

    private StepPadrao sp = new StepPadrao();
    private File arquivo;
    private ImportaStepPadrao importeStepPadrao = new ImportaStepPadrao();
    private final ManipulaDadosSQLite bd;

    /**
     * Creates new form GUIImportaStepPadrao
     */
    public ImportStepDefaultScreenView() throws SQLException, ClassNotFoundException {
        this.bd = new ManipulaDadosSQLite();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPlanilha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bntAbrirPlanilha = new javax.swing.JButton();
        bntImportaStepPadrao = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Importa Step Padrão");

        textPlanilha.setEditable(false);
        textPlanilha.setAutoscrolls(false);

        jLabel1.setText("Planilha:");

        bntAbrirPlanilha.setText("Abrir");
        bntAbrirPlanilha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAbrirPlanilhaMouseClicked(evt);
            }
        });

        bntImportaStepPadrao.setText("Importar");
        bntImportaStepPadrao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntImportaStepPadraoMouseClicked(evt);
            }
        });

        bntCancelar.setText("Cancelar");
        bntCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPlanilha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntAbrirPlanilha)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(bntImportaStepPadrao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(bntCancelar)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPlanilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(bntAbrirPlanilha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntImportaStepPadrao)
                    .addComponent(bntCancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAbrirPlanilhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAbrirPlanilhaMouseClicked
        // TODO add your handling code here:
        FileFilter extensao = new FileNameExtensionFilter("Planilhas de Carga (*.xlsx)", "xlsx");
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        file.setDialogTitle("Selecione a planilha para importar:");

        file.setFileFilter(extensao);
        int i = file.showSaveDialog(null);

        if (i == 1) {
            //             JtextFieldLocal.setText("");
        } else {
            arquivo = file.getSelectedFile();

            System.out.println(arquivo.getPath());
            textPlanilha.setText(arquivo.getPath());
        }


    }//GEN-LAST:event_bntAbrirPlanilhaMouseClicked

    private void bntImportaStepPadraoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntImportaStepPadraoMouseClicked
         final Frame GUIPrincipal = new MainScreenView();
        new SwingWorker() {
            List<StepPadrao> listSp = new ArrayList<StepPadrao>();
            JDialog aguarde = new WaitScreenView((JFrame) GUIPrincipal, true);
            @Override
            protected Object doInBackground() throws Exception {
                aguarde.setLocationRelativeTo(GUIPrincipal);
                aguarde.setVisible(true);
                if (textPlanilha.getText().equals("") || textPlanilha.getText() == null) {
                    aguarde.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Favor selecionar uma planilha", "Erro", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        if (importeStepPadrao.verificaVersao(arquivo.getPath())) {
                            listSp = importeStepPadrao.getStepPadraoPlanilha(arquivo.getPath());
                            bd.insertStepPadrao(listSp);
                            System.out.println("Importe realizado com sucesso!");
                            JOptionPane.showMessageDialog(null, "Importe realizado com sucesso!", "Importação", JOptionPane.INFORMATION_MESSAGE);
                            
                        } else {
                            aguarde.setVisible(false);
                            JOptionPane.showMessageDialog(null, "A versão da base dados local é maior do que a versão da planilha."+ System.getProperty("line.separator")+ "Versão da base de dados:"+ bd.getVersaoStepPadrao()+ System.getProperty("line.separator")+ "Versão da planilha: "+ importeStepPadrao.getVersaoPlanilha(arquivo.getPath()), "Versionamento", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Ocorreu o erro: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    } catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(null, "Ocorreu o erro: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Ocorreu o erro: " + ex.getMessage()+ " Causa: " + ex.getCause(), "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }

                return null;

            }

            @Override
            protected void done() {
                aguarde.dispose();
            }
        }.execute();


    }//GEN-LAST:event_bntImportaStepPadraoMouseClicked

    private void bntCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bntCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAbrirPlanilha;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntImportaStepPadrao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textPlanilha;
    // End of variables declaration//GEN-END:variables
    public void centralizaJanela() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

}
