/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accenture.view;

import java.awt.GridLayout;
import javax.swing.JMenuBar;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.LayoutManager;

/**
 *
 * @author brucilin.de.gouveia
 */
public class MenuLateralView extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuLateralView
     */
    public MenuLateralView() {
        initComponents();
        putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new VerticalMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setTitle("Menu Rápido");
        setToolTipText("Menu Rápido");
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(60, 2147483647));
        setVisible(true);

        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\brucilin.de.gouveia\\Pictures\\CT\\report1.png")); // NOI18N
        jMenu1.setText("File");
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu1.setMaximumSize(new java.awt.Dimension(200, 200));
        jMenu1.setMinimumSize(new java.awt.Dimension(40, 40));
        jMenuBar1.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleName("Relatórios");

        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\brucilin.de.gouveia\\Pictures\\CT\\report1.png")); // NOI18N
        jMenu2.setText("Relatórios");
        jMenu2.setBorderPainted(true);
        jMenu2.setMaximumSize(new java.awt.Dimension(200, 200));
        jMenu2.setMinimumSize(new java.awt.Dimension(40, 40));
        jMenuBar1.add(jMenu2);
        jMenu2.getAccessibleContext().setAccessibleName("Tickets");

        jMenu3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\brucilin.de.gouveia\\Pictures\\CT\\report1.png")); // NOI18N
        jMenu3.setText("jMenu3");
        jMenu3.setMinimumSize(new java.awt.Dimension(40, 40));
        jMenuBar1.add(jMenu3);

        jMenu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\brucilin.de.gouveia\\Pictures\\CT\\report1.png")); // NOI18N
        jMenu4.setText("jMenu4");
        jMenuBar1.add(jMenu4);

        jMenu5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu5.setIcon(new javax.swing.ImageIcon("C:\\Users\\brucilin.de.gouveia\\Pictures\\CT\\report1.png")); // NOI18N
        jMenu5.setText("jMenu5");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}




class VerticalMenuBar extends JMenuBar {
  private static final LayoutManager grid = new GridLayout(0,1);
  public VerticalMenuBar() {
    setLayout(grid);
  }
}
